// English counterparts of the existing educational questions. IDs, answer order,
// correct indices and references are inherited from the Vietnamese source.
export const englishQuestions = {
  response: {
    category: 'Recognizing an emergency', scene: 'The right action.\nA chance to help.',
    imageAlt: 'First aid practice with a manikin in an office',
    question: 'Someone suddenly collapses. Once the scene is safe, what should you do first?',
    answers: ['Check responsiveness and breathing, and call for help', 'Give the person water', 'Wait for the person to regain consciousness', 'Immediately pull the person to their feet'],
    hint: 'Start by assessing the condition of the person who needs help.',
    explanation: 'Check responsiveness and normal breathing for no more than 10 seconds. If the person is unresponsive and not breathing normally, activate emergency services, start CPR and use an AED when available.',
  },
  safety: {
    category: 'Scene safety', scene: 'Keep yourself safe.\nBe safe to help.',
    imageAlt: 'Safety training at a construction site',
    question: 'Before approaching an injured person, what should take priority?',
    answers: ['Take photos of the scene', 'Check that the surrounding area is safe', 'Move every nearby object', 'Rush over regardless of danger'],
    hint: 'You can help effectively only when you are not putting yourself in danger.',
    explanation: 'Look for hazards such as electricity, traffic or fire before approaching. Do not put yourself in danger.',
  },
  cpr: {
    category: 'Cardiopulmonary resuscitation', scene: 'Observe calmly.\nTake action.',
    imageAlt: 'CPR practice on a manikin',
    question: 'An adult is unresponsive and only gasping. After activating emergency services, what should you do?',
    answers: ['Wait for breathing to return', 'Give the person sugar water', 'Start CPR and use an AED when available', 'Help the person sit up'],
    hint: 'Gasping is not normal breathing.',
    explanation: 'Unresponsiveness and the absence of normal breathing indicate the need for CPR. Ask someone to call emergency services and get an AED; follow the dispatcher’s instructions.',
  },
  rate: {
    category: 'Cardiopulmonary resuscitation', scene: 'The right rhythm.\nA chance at life.',
    imageAlt: 'Learners practicing chest compressions on a manikin',
    question: 'What is the recommended chest compression rate for adult CPR?',
    answers: ['40–60 compressions/minute', '60–80 compressions/minute', '160–180 compressions/minute', '100–120 compressions/minute'],
    hint: 'Chest compressions should be steady, fast and continuous.',
    explanation: 'Give chest compressions at 100–120 per minute, allow the chest to fully recoil after each compression and minimize interruptions.',
  },
  aed: {
    category: 'Using an AED', scene: 'Listen to the instructions.\nHelp step by step.',
    imageAlt: 'A first aid education session',
    question: 'An AED is analyzing the heart rhythm or preparing to deliver a shock. What must you ensure?',
    answers: ['No one is touching the person receiving care', 'Someone holds the person’s arms firmly', 'Keep touching the person to check responsiveness', 'Remove the electrode pads'],
    hint: 'Follow the device’s voice instructions.',
    explanation: 'Do not touch the person while the AED is analyzing or delivering a shock. Resume CPR as soon as the device instructs you to do so.',
  },
  bleeding: {
    category: 'Managing bleeding', scene: 'Recognize it early.\nHelp promptly.',
    imageAlt: 'Instruction on using a first aid kit',
    question: 'An external wound is bleeding heavily. What is an appropriate initial action?',
    answers: ['Keep lifting the dressing to look', 'Apply firm, continuous direct pressure to the wound', 'Only wipe away the blood around it', 'Let the wound dry on its own'],
    hint: 'Use gauze or a clean cloth to apply pressure where the bleeding is occurring.',
    explanation: 'Call emergency services for severe bleeding. Use gauze or a clean cloth to apply firm, continuous direct pressure; protect yourself from contact with blood.',
  },
  burn: {
    category: 'First aid for burns', scene: 'Practical knowledge.\nEveryday protection.',
    imageAlt: 'Teachers attending a first aid class',
    question: 'How should you cool a small thermal burn?',
    answers: ['Apply toothpaste immediately', 'Place ice directly on the skin', 'Cool it under cool running water for at least 20 minutes', 'Apply cooking oil to the burn'],
    hint: 'Cool water helps reduce heat in the burned area.',
    explanation: 'Cool the burn under gently running cool water for at least 20 minutes. Keep the rest of the body warm; do not apply ice directly or use toothpaste.',
  },
  breathing: {
    category: 'Monitoring the person', scene: 'Stay and help.\nWatch for changes.',
    imageAlt: 'Instruction in care and first aid skills',
    question: 'A person is unresponsive but breathing normally, with no signs of injury. What should you do?',
    answers: ['Start chest compressions immediately', 'Give the person water', 'Leave the person alone', 'Call emergency services, use the recovery position and monitor breathing'],
    hint: 'Keep the airway clear and continue monitoring.',
    explanation: 'Use the recovery position when appropriate, call emergency services and monitor breathing. If breathing becomes abnormal, start CPR as instructed.',
  },
  help: {
    category: 'Calling for help', scene: 'Coordinate clearly.\nHelp more effectively.',
    imageAlt: 'Learners discussing first aid with an instructor',
    question: 'Other people are nearby while you provide emergency care. What is the best way to ask for help?',
    answers: ['Assign someone to call emergency services and get an AED if available', 'Wait for people to organize themselves', 'Ask everyone to leave', 'Stop helping to record a video'],
    hint: 'Give a clear task to a specific person.',
    explanation: 'Ask one person to call emergency services and another to find an AED if available. Coordinate with others helping and follow the dispatcher’s instructions.',
  },
  monitor: {
    category: 'Ongoing care', scene: 'First aid is a skill.\nPractice to prepare.',
    imageAlt: 'First aid practice at a GHME training class',
    question: 'After calling emergency services and providing initial first aid, what should you do while waiting for help?',
    answers: ['Leave when the person seems fine', 'Stay, reassure the person and monitor changes in their condition', 'Give the person food immediately to restore energy', 'Stop monitoring entirely'],
    hint: 'The person’s condition may change while waiting for medical personnel.',
    explanation: 'Stay if it is safe, reassure the person and monitor responsiveness and breathing. Adapt your care to the person’s condition and the dispatcher’s instructions.',
  },
};
