// Browser acceptance checks for the header, using the bundled Playwright runtime.
const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const output = path.join(root, 'docs/design-reference/header-search-refinement');
fs.mkdirSync(output, { recursive: true });
const url = 'http://127.0.0.1:4173/';
const results = [], errors = [], failedAssets = [];
const shots = { animations: 'disabled' };
const record = (name, detail = '') => results.push({ name, status: 'PASS', detail });
(async () => {
  const browser = await chromium.launch({ channel: 'msedge', headless: true });
  try {
    const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
    page.on('pageerror', e => errors.push(e.message));
    page.on('console', m => { if (m.type() === 'error') errors.push(m.text()); });
    page.on('response', r => { if (r.status() >= 400) failedAssets.push(r.url()); });
    page.on('requestfailed', r => failedAssets.push(r.url()));
    await page.goto(url);
    await page.evaluate(() => document.fonts.ready);
    if (process.argv.includes('--before')) {
      await page.screenshot({ ...shots, path: path.join(output, 'header-before-1440.png') });
      return;
    }
    const header = page.locator('.premium-header');
    const course = header.locator('[aria-controls="course-dropdown"]');
    const product = header.locator('[aria-controls="product-dropdown"]');
    const coursePanel = header.locator('#course-dropdown');
    const productPanel = header.locator('#product-dropdown');
    const noOverflow = async () => assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, 'No horizontal page overflow');
    const shot = async name => page.screenshot({ ...shots, path: path.join(output, name + '.png') });
    for (const width of [1440, 1200, 1024, 768, 430, 375]) {
      await page.setViewportSize({ width, height: width < 576 ? 844 : 1000 });
      await noOverflow();
      const bounds = await header.locator('.nav-wrap').boundingBox();
      assert.equal(bounds.height, width >= 1100 ? 92 : width < 768 ? 132 : 80);
      const utilityBounds = await header.locator('.utility').boundingBox();
      assert.ok(utilityBounds.height >= 38 && utilityBounds.height <= 48);
      const searchBounds = await header.locator('#search-form').boundingBox();
      assert.ok(searchBounds.y >= bounds.y && searchBounds.y + searchBounds.height <= bounds.y + bounds.height);
      assert.ok(searchBounds.x >= bounds.x && searchBounds.x + searchBounds.width <= bounds.x + bounds.width + 1);
      assert.equal(searchBounds.height, width < 768 ? 48 : 46);
      if (width >= 1200) assert.ok(searchBounds.width >= 320 && searchBounds.width <= 400);
      await header.locator('.brand').evaluate(img => img.decode());
      await page.evaluate(() => document.activeElement.blur());
      await shot('header-after-' + width);
      await header.screenshot({ ...shots, path: path.join(output, 'header-only-' + width + '.png') });
      if (width >= 1100) {
        const before = await page.locator('.hero').boundingBox();
        await course.hover();
        await coursePanel.waitFor({ state: 'visible' });
        const panelBox = await coursePanel.boundingBox();
        assert.ok(Math.abs(panelBox.y - bounds.y - bounds.height) < 1, 'No hover gap');
        assert.ok(Math.abs(panelBox.width - bounds.width) < 1, 'Panel spans header container');
        assert.deepEqual(await page.locator('.hero').boundingBox(), before, 'Opening panel does not shift hero');
        await coursePanel.locator('[data-header-category="doctor"]').hover();
        assert.equal(await header.locator('#header-doctor').isVisible(), true);
        await coursePanel.locator('[data-header-category="bpec"]').hover();
        if (width === 1440) await shot('mega-courses-1440');
        await product.hover();
        assert.equal(await coursePanel.isVisible(), false);
        assert.equal(await productPanel.isVisible(), true);
        if (width === 1440) await shot('mega-products-aed-1440');
        await productPanel.locator('[data-header-category="kits"]').hover();
        assert.equal(await header.locator('#header-kits').isVisible(), true);
        await header.locator('#header-kits img').evaluateAll(imgs => Promise.all(imgs.map(i => i.decode())));
        if (width === 1440) await shot('mega-products-kits-1440');
        await productPanel.locator('[data-header-category="training"]').click();
        assert.equal(await header.locator('#header-training').isVisible(), true);
        await page.keyboard.press('Escape');
        assert.equal(await productPanel.isVisible(), false);
        assert.equal(await product.evaluate(el => el === document.activeElement), true);
      } else {
        const heroBefore = await page.locator('.hero').boundingBox();
        await header.locator('.menu-toggle').click();
        assert.equal(await header.locator('.header-drawer-close').evaluate(el => el === document.activeElement), true);
        assert.equal(await page.evaluate(() => document.body.style.overflow), 'hidden');
        assert.equal(await page.locator('main').evaluate(el => el.inert), true);
        assert.equal(await header.locator('#search-form').evaluate(el => el.inert), true);
        await course.click();
        await coursePanel.locator('[data-header-category="doctor"]').click();
        assert.equal(await header.locator('#header-doctor').isVisible(), true);
        await coursePanel.locator('[data-header-category="doctor"]').click();
        assert.equal(await header.locator('#header-doctor').isVisible(), false);
        await coursePanel.locator('[data-header-category="bpec"]').click();
        await noOverflow();
        if (width === 430 || width === 375) await shot('mobile-courses-' + width);
        await product.click();
        await productPanel.locator('[data-header-category="kits"]').click();
        await header.locator('#header-kits img').evaluateAll(imgs => Promise.all(imgs.map(i => i.decode())));
        await noOverflow();
        if (width === 430 || width === 768) await shot('mobile-products-' + width);
        await header.locator('.header-drawer-close').click();
        assert.equal(await header.locator('#navigation').isVisible(), false);
        assert.equal(await page.evaluate(() => document.body.style.overflow), '');
        assert.equal(await page.locator('main').evaluate(el => el.inert), false);
        assert.equal(await header.locator('#search-form').evaluate(el => el.inert), false);
        assert.equal(await header.locator('.menu-toggle').evaluate(el => el === document.activeElement), true);
        assert.deepEqual(await page.locator('.hero').boundingBox(), heroBefore);
      }
      record('Responsive ' + width);
    }
    await page.setViewportSize({ width: 1440, height: 1000 });
    await page.mouse.move(1400, 900);
    await course.focus();
    await page.keyboard.press('ArrowDown');
    assert.equal(await coursePanel.isVisible(), true);
    await page.keyboard.press('ArrowDown');
    assert.equal(await header.locator('#header-doctor').isVisible(), true);
    await page.keyboard.press('ArrowRight');
    assert.equal(await header.locator('#header-doctor a').first().evaluate(el => el === document.activeElement), true);
    await page.keyboard.press('ArrowLeft');
    assert.equal(await coursePanel.locator('[data-header-category="doctor"]').evaluate(el => el === document.activeElement), true);
    await page.keyboard.press('Escape');
    assert.equal(await course.evaluate(el => el === document.activeElement), true);
    await page.keyboard.press('Enter');
    assert.equal(await coursePanel.isVisible(), true);
    await page.keyboard.press('Enter');
    assert.equal(await coursePanel.isVisible(), false);
    record('Keyboard navigation, category arrows and Escape focus return');
    await course.hover();
    await course.click();
    assert.equal(await coursePanel.isVisible(), true, 'First click after hover keeps panel open');
    await course.click();
    assert.equal(await coursePanel.isVisible(), false);
    await product.hover();
    await page.mouse.move(1400, 850);
    await page.locator('.hero').click({ position: { x: 40, y: 40 } });
    assert.equal(await productPanel.isVisible(), false);
    record('Hover, click, category switching and outside click');
    await course.hover();
    const triggerBox = await course.boundingBox();
    const panelBox = await coursePanel.boundingBox();
    await page.mouse.move(triggerBox.x + triggerBox.width / 2, panelBox.y + 25, { steps: 15 });
    await page.waitForTimeout(250);
    assert.equal(await coursePanel.isVisible(), true);
    await page.keyboard.press('Escape');
    record('No hover gap or flicker while crossing into panel');
    for (const [id, category] of [['aed', 'aed'], ['personal', 'kits'], ['office', 'kits'], ['travel', 'kits'], ['cpr', 'training'], ['training', 'training']]) {
      await page.evaluate(() => scrollTo(0, 0));
      await product.hover();
      await productPanel.locator('[data-header-category="' + category + '"]').hover();
      await productPanel.locator('[data-header-product="' + id + '"]').click();
      assert.equal(await page.locator('#product-' + id).isVisible(), true);
      assert.equal(await productPanel.isVisible(), false);
      assert.equal(await page.evaluate(() => location.hash), '#product-' + id);
    }
    record('All six product destinations select the correct existing showcase panel');
    await page.evaluate(() => scrollTo(0, 0));
    await header.locator('.nav-actions [data-info="login"]').click();
    assert.equal(await page.locator('#info-dialog').evaluate(el => el.open), true);
    await page.locator('#info-dialog .dialog-close').click();
    await header.locator('.header-utility-cta').click();
    assert.equal(await page.evaluate(() => location.hash), '#consultation');
    record('Consultation anchor and existing login prototype dialog');
    await page.setViewportSize({ width: 390, height: 844 });
    await page.evaluate(() => scrollTo(0, 0));
    await header.locator('.menu-toggle').click();
    await page.keyboard.press('Shift+Tab');
    assert.equal(await header.locator('.nav-actions [data-info="login"]').evaluate(el => el === document.activeElement), true);
    await page.keyboard.press('Tab');
    assert.equal(await header.locator('.header-drawer-close').evaluate(el => el === document.activeElement), true);
    await header.locator('.nav-actions [data-info="login"]').click();
    assert.equal(await page.locator('#info-dialog').evaluate(el => el.open && !el.inert), true);
    assert.equal(await page.evaluate(() => document.body.style.overflow), '');
    await page.locator('#info-dialog .dialog-close').click();
    await header.locator('.menu-toggle').click();
    await page.keyboard.press('Escape');
    assert.equal(await header.locator('#navigation').isVisible(), false);
    await header.locator('.menu-toggle').click();
    await page.setViewportSize({ width: 1280, height: 1000 });
    assert.equal(await page.evaluate(() => document.body.style.overflow), '');
    assert.equal(await page.locator('main').evaluate(el => el.inert), false);
    record('Drawer focus loop, Escape, login, scroll lock and breakpoint cleanup');
    await page.setViewportSize({ width: 1024, height: 900 });
    await page.evaluate(() => scrollTo({ top: 0, behavior: 'instant' }));
    await header.locator('.menu-toggle').click();
    await header.locator('.header-backdrop').click({ position: { x: 30, y: 80 } });
    assert.equal(await header.locator('#navigation').isVisible(), false);
    assert.equal(await header.locator('#search-form').evaluate(el => el.inert), false);
    await page.setViewportSize({ width: 1440, height: 1000 });
    record('Tablet backdrop covers header controls and closes drawer');
    await page.evaluate(() => scrollTo(0, 350));
    assert.equal((await header.boundingBox()).y < 0, true, 'Existing header is non-sticky and scrolls naturally');
    await noOverflow();
    record('Scrolling preserves existing non-sticky behavior');
    const links = await header.locator('a[href]').evaluateAll(els => els.map(el => el.getAttribute('href')));
    for (const href of links) {
      const parsed = new URL(href, url);
      const targetPath = parsed.pathname === '/' ? 'index.html' : parsed.pathname.slice(1);
      assert.ok(fs.existsSync(path.join(root, targetPath)), href);
      if (parsed.hash) assert.ok(fs.readFileSync(path.join(root, targetPath), 'utf8').includes('id="' + parsed.hash.slice(1) + '"'), href);
    }
    await header.locator('img').evaluateAll(imgs => Promise.all(imgs.map(i => i.decode())));
    record('Header links and image assets');
    for (const width of [1440, 1024, 375]) {
      await page.setViewportSize({ width, height: 900 });
      await page.evaluate(() => scrollTo({ top: 0, behavior: 'instant' }));
      await header.locator('#search').fill('BPEC');
      await header.locator('#search-form [type="submit"]').click();
      assert.equal(await page.locator('#info-dialog').evaluate(el => el.open), true);
      assert.ok(await page.locator('#info-dialog a[href="#program-1"]').isVisible());
      await page.locator('#info-dialog .dialog-close').click();
      await header.locator('#search').fill('chương trình không tồn tại xyz');
      await header.locator('#search').press('Enter');
      assert.ok((await page.locator('#info-dialog').innerText()).includes('Chưa có chương trình phù hợp'));
      await page.locator('#info-dialog .dialog-close').click();
      await header.locator('#search').fill('');
      await header.locator('.language').click();
      assert.equal(await page.locator('#info-dialog').evaluate(el => el.open), true);
      assert.ok((await page.locator('#info-dialog').innerText()).includes('Ngôn ngữ'));
      await page.locator('#info-dialog .dialog-close').click();
    }
    record('Search button, Enter, matching/empty results and existing language dialog on desktop, tablet and phone');
    await page.setViewportSize({ width: 1440, height: 1000 });
    await page.evaluate(() => scrollTo({ top: 0, behavior: 'instant' }));
    await course.focus();
    await page.keyboard.press('ArrowDown');
    await coursePanel.locator('[data-header-category="bpec"]').click();
    await coursePanel.locator('#header-bpec a').first().click();
    await page.waitForURL('**/courses/program-1.html');
    assert.equal(await page.locator('h1').innerText(), 'Cấp cứu ngoại viện cơ bản (BPEC)');
    await page.goto(url);
    await course.focus();
    await page.keyboard.press('ArrowDown');
    await coursePanel.locator('[data-header-category="doctor"]').click();
    await header.locator('#header-doctor a').first().click();
    await page.waitForURL('**/courses/program-2.html');
    record('Both course detail links navigate successfully');
    const original = fs.readFileSync(path.join(os.tmpdir(), 'ghme-header-main-redesign-original/index.html'), 'utf8');
    const current = fs.readFileSync(path.join(root, 'index.html'), 'utf8');
    assert.equal(current.slice(current.indexOf('  <main')), original.slice(original.indexOf('  <main')));
    assert.equal(fs.readFileSync(path.join(root, 'assets/css/styles.css'), 'utf8'), fs.readFileSync(path.join(os.tmpdir(), 'ghme-header-main-redesign-original/styles.css'), 'utf8'));
    record('All content after header and existing styles.css preserved byte-for-byte');
    assert.deepEqual(errors, [], 'No console or runtime errors');
    assert.deepEqual(failedAssets, [], 'No failed asset requests');
    fs.writeFileSync(path.join(output, 'qa-result.json'), JSON.stringify({ results, errors, failedAssets, links }, null, 2));
    console.log(JSON.stringify({ results, errors, failedAssets }, null, 2));
  } finally { await browser.close(); }
})().catch(error => {
  fs.writeFileSync(path.join(output, 'qa-result.json'), JSON.stringify({ results, errors, failedAssets, failure: error.message }, null, 2));
  console.error(error); process.exitCode = 1;
});
